export const LOGIN= 'LOGIN'

export const LIST_LOCATIONS= 'LIST_LOCATIONS'
export const LIST_LOCATIONS_SUCCESS= 'LIST_LOCATIONS_SUCCESS'

export const LIST_ARTISTS= 'LIST_ARTISTS'
export const LIST_ARTISTS_SUCCESS= 'LIST_ARTISTS_SUCCESS'

export const LIST_OBRAS= 'LIST_OBRAS'
export const LIST_OBRAS_SUCCESS= 'LIST_OBRAS_SUCCESS'
export const LIST_OBRAS_TOUR= 'LIST_OBRAS_TOUR'
export const LIST_OBRAS_TOUR_SUCCESS= 'LIST_OBRAS_TOUR_SUCCESS'

export const LIST_TOURS = 'LIST_TOURS'
export const LIST_TOURS_SUCCESS = 'LIST_TOURS_SUCCESS'
export const GET_TOUR = 'GET_TOUR'
export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS'
export const GET_RATING_TOUR = 'GET_RATING_TOUR'
export const GET_RATING_TOUR_SUCCESS = 'GET_RATING_TOUR_SUCCESS'


export const LIST_USERS = 'LIST_USERS'
export const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS'

export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
