export const LOGIN= 'LOGIN'

export const LIST_LOCATIONS= 'LIST_LOCATIONS'
export const LIST_LOCATIONS_SUCCESS= 'LIST_LOCATIONS_SUCCESS'

export const LIST_ARTISTS= 'LIST_ARTISTS'
export const LIST_ARTISTS_SUCCESS= 'LIST_ARTISTS_SUCCESS'

export const LIST_OBRAS= 'LIST_OBRAS'
export const LIST_OBRAS_SUCCESS= 'LIST_OBRAS_SUCCESS'
export const LIST_OBRAS_TOUR= 'LIST_OBRAS_TOUR'
export const LIST_OBRAS_TOUR_SUCCESS= 'LIST_OBRAS_TOUR_SUCCESS'

export const LIST_TOURS = 'LIST_TOURS'
export const LIST_TOURS_SUCCESS = 'LIST_TOURS_SUCCESS'
export const GET_TOUR = 'GET_TOUR'
export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS'
export const GET_RATING_TOUR = 'GET_RATING_TOUR'
export const GET_RATING_TOUR_SUCCESS = 'GET_RATING_TOUR_SUCCESS'


export const LIST_USERS = 'LIST_USERS'
export const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS'

export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'


export const EDIT_PROFILE_PIC = 'EDIT_PROFILE_PIC'
export const EDIT_PROFILE_PIC_SUCCESS = 'EDIT_PROFILE_PIC_SUCCESS'

export const RESERVE = 'RESERVE'
export const RESERVE_SUCCESS = 'RESERVE_SUCCESS'

export const GET_RESERVA = 'GET_RESERVA'
export const GET_RESERVA_SUCCESS = 'GET_RESERVA_SUCCESS'

export const RESET_RESERVA = 'RESET_RESERVA'

export const GET_RESERVAS = 'GET_RESERVAS'
export const GET_RESERVAS_SUCCESS = 'GET_RESERVAS_SUCCESS'

export const SEND_FEEDBACK = 'SEND_FEEDBACK'
export const SEND_FEEDBACK_SUCCESS = 'SEND_FEEDBACK_SUCCESS'

export const LIST_RESERVAS = 'LIST_RESERVAS'
export const LIST_RESERVAS_SUCCESS = 'LIST_RESERVAS_SUCCESS'

export const ADD_ARTIST = 'ADD_ARTIST'
export const ADD_ARTIST_SUCCESS = 'ADD_ARTIST_SUCCESS'

export const ADD_LOCATION = 'ADD_LOCATION'
export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS'

export const ADD_OBRA = 'ADD_OBRA'
export const ADD_OBRA_SUCCESS = 'ADD_OBRA_SUCCESS'

export const ADD_TOUR = 'ADD_TOUR'
export const ADD_TOUR_SUCCESS = 'ADD_TOUR_SUCCESS'

export const UPDATE_ARTIST = 'UPDATE_ARTIST'
export const UPDATE_ARTIST_SUCCESS = 'UPDATE_ARTIST_SUCCESS'

export const UPDATE_LOCATION = 'UPDATE_LOCATION'
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS'

export const UPDATE_OBRA = 'UPDATE_OBRA'
export const UPDATE_OBRA_SUCCESS = 'UPDATE_OBRA_SUCCESS'

export const UPDATE_TOUR = 'UPDATE_TOUR'
export const UPDATE_TOUR_SUCCESS = 'UPDATE_TOUR_SUCCESS'