export const LOGIN= 'LOGIN'

export const LIST_LOCATIONS= 'LIST_LOCATIONS'
export const LIST_LOCATIONS_SUCCESS= 'LIST_LOCATIONS_SUCCESS'

export const LIST_ARTISTS= 'LIST_ARTISTS'
export const LIST_ARTISTS_SUCCESS= 'LIST_ARTISTS_SUCCESS'

export const LIST_OBRAS= 'LIST_OBRAS'
export const LIST_OBRAS_SUCCESS= 'LIST_OBRAS_SUCCESS'

export const LIST_TOURS = 'LIST_TOURS'
export const LIST_TOURS_SUCCESS = 'LIST_TOURS_SUCCESS'